import { pgTable, uuid, timestamp, text, jsonb, boolean, varchar } from "drizzle-orm/pg-core";
import { apps } from "./apps";

export const appPages = pgTable("app_pages", {
  id: uuid("id").primaryKey().defaultRandom(),
  createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow(),
  slug: text("slug").notNull(),
  lang: text("lang").notNull().default(""),
  seo: jsonb("seo").default({}),
  app: uuid("app").notNull().references(() => apps.id),
  buildTime: boolean("buildTime").default(false),
  name: text("name").notNull(),
  primaryPage: uuid("primaryPage"),
  blocks: jsonb("blocks").default([]),
  currentEditor: text("currentEditor"),
  changes: jsonb("changes"),
  collection: text("collection").default("page"),
  online: boolean("online").default(false),
  parent: uuid("parent"),
  pageType: text("pageType"),
  lastSaved: timestamp("lastSaved", { withTimezone: true }),
  dynamic: boolean("dynamic").default(false),
  libRefId: uuid("libRefId"),
  dynamicSlugCustom: varchar("dynamicSlugCustom").default(""),
  metadata: jsonb("metadata").default({}),
  tracking: jsonb("tracking").default({}),
  jsonld: jsonb("jsonld").default({}),
  globalJsonLds: jsonb("globalJsonLds").default([]),
});

export const appPagesOnline = pgTable("app_pages_online", {
  id: uuid("id").primaryKey(),
  createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow(),
  slug: text("slug").notNull(),
  lang: text("lang").notNull().default(""),
  seo: jsonb("seo").default({}),
  app: uuid("app").notNull().references(() => apps.id),
  buildTime: boolean("buildTime").default(false),
  name: text("name").notNull(),
  primaryPage: uuid("primaryPage"),
  blocks: jsonb("blocks").default([]),
  currentEditor: text("currentEditor"),
  changes: jsonb("changes"),
  collection: text("collection").default("page"),
  partialBlocks: text("partialBlocks"),
  links: text("links"),
  online: boolean("online").default(true),
  pageType: text("pageType"),
  parent: uuid("parent"),
  lastSaved: timestamp("lastSaved", { withTimezone: true }),
  dynamic: boolean("dynamic").default(false),
  libRefId: uuid("libRefId"),
  dynamicSlugCustom: varchar("dynamicSlugCustom").default(""),
  metadata: jsonb("metadata").default({}),
  tracking: jsonb("tracking").default({}),
  jsonld: jsonb("jsonld").default({}),
  globalJsonLds: jsonb("globalJsonLds").default([]),
});

export const appPagesRevisions = pgTable("app_pages_revisions", {
  uid: uuid("uid").primaryKey().defaultRandom(),
  id: uuid("id").notNull(),
  createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow(),
  slug: text("slug").notNull(),
  lang: text("lang").notNull().default(""),
  seo: jsonb("seo").default({}),
  app: uuid("app").notNull().references(() => apps.id),
  buildTime: boolean("buildTime").default(false),
  name: text("name").notNull(),
  primaryPage: uuid("primaryPage"),
  blocks: jsonb("blocks").default([]),
  currentEditor: text("currentEditor"),
  changes: jsonb("changes"),
  collection: text("collection").default("page"),
  partialBlocks: text("partialBlocks"),
  links: text("links"),
  online: boolean("online").default(true),
  pageType: text("pageType"),
  parent: uuid("parent"),
  lastSaved: timestamp("lastSaved", { withTimezone: true }),
  dynamic: boolean("dynamic").default(false),
  type: varchar("type").default("published"),
  libRefId: uuid("libRefId"),
  dynamicSlugCustom: varchar("dynamicSlugCustom").default(""),
  metadata: jsonb("metadata").default({}),
  tracking: jsonb("tracking").default({}),
  jsonld: jsonb("jsonld").default({}),
  globalJsonLds: jsonb("globalJsonLds").default([]),
});

export const appOnlinePages = pgTable("app_online_pages", {
  id: uuid("id").primaryKey().defaultRandom(),
  createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow(),
  slug: text("slug").notNull(),
  lang: text("lang").notNull().default(""),
  seo: jsonb("seo").default({}),
  app: uuid("app").notNull().references(() => apps.id),
  buildTime: boolean("buildTime").default(false),
  status: text("status").default("UNPUBLISHED"),
  name: text("name").notNull(),
  global: boolean("global").default(false),
  primaryPage: uuid("primaryPage"),
  type: text("type").default(""),
  blocks: jsonb("blocks").default([]),
  globalBlocks: text("globalBlocks").default(""),
  currentEditor: uuid("currentEditor"),
  links: text("links").default(""),
  online: boolean("online").default(false),
  page: uuid("page"),
  collection: text("collection").default("page"),
  parent: uuid("parent"),
  pageType: text("pageType"),
});
