-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.app_api_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  apiKey text DEFAULT ''::text,
  app uuid,
  status text DEFAULT 'ACTIVE'::text,
  CONSTRAINT app_api_keys_pkey PRIMARY KEY (id),
  CONSTRAINT app_api_keys_app_fkey FOREIGN KEY (app) REFERENCES public.apps(id)
);
CREATE TABLE public.app_assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  app uuid,
  name text,
  description text,
  url text,
  size text,
  folderId text,
  thumbnailUrl text,
  duration numeric,
  format text,
  width numeric,
  height numeric,
  createdBy text,
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  type text,
  updatedAt timestamp with time zone,
  CONSTRAINT app_assets_pkey PRIMARY KEY (id),
  CONSTRAINT app_assets_app_fkey FOREIGN KEY (app) REFERENCES public.apps(id)
);
CREATE TABLE public.app_domains (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  app uuid,
  hosting text DEFAULT 'vercel'::text,
  hostingProjectId text DEFAULT 'env'::text,
  subdomain text,
  domain text,
  domainConfigured boolean DEFAULT false,
  CONSTRAINT app_domains_pkey PRIMARY KEY (id),
  CONSTRAINT app_domains_app_fkey FOREIGN KEY (app) REFERENCES public.apps(id)
);
CREATE TABLE public.app_form_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  app uuid,
  formData json,
  additionalData json,
  formName text DEFAULT ''::text,
  pageUrl text,
  CONSTRAINT app_form_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT app_form_submissions_app_fkey FOREIGN KEY (app) REFERENCES public.apps(id)
);
CREATE TABLE public.app_online_pages (
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  slug text NOT NULL,
  lang text NOT NULL DEFAULT ''::text,
  seo jsonb DEFAULT '{}'::jsonb,
  app uuid NOT NULL,
  buildTime boolean DEFAULT false,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  status text DEFAULT 'UNPUBLISHED'::text,
  name text NOT NULL,
  global boolean DEFAULT false,
  primaryPage uuid,
  type text DEFAULT ''::text,
  blocks jsonb DEFAULT '[]'::jsonb,
  globalBlocks text DEFAULT ''::text,
  currentEditor uuid,
  links text DEFAULT ''::text,
  online boolean DEFAULT false,
  page uuid,
  collection text DEFAULT 'page'::text,
  parent uuid,
  pageType text,
  CONSTRAINT app_online_pages_pkey PRIMARY KEY (id),
  CONSTRAINT app_online_pages_app_fkey FOREIGN KEY (app) REFERENCES public.apps(id),
  CONSTRAINT app_online_pages_currentEditor_fkey FOREIGN KEY (currentEditor) REFERENCES auth.users(id),
  CONSTRAINT app_online_pages_page_fkey FOREIGN KEY (page) REFERENCES public.app_pages(id)
);
CREATE TABLE public.app_pages (
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  slug text NOT NULL,
  lang text NOT NULL DEFAULT ''::text,
  seo jsonb DEFAULT '{}'::jsonb,
  app uuid NOT NULL,
  buildTime boolean DEFAULT false,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  primaryPage uuid,
  blocks jsonb DEFAULT '[]'::jsonb,
  currentEditor text,
  changes jsonb,
  collection text DEFAULT 'page'::text,
  online boolean DEFAULT false,
  parent uuid,
  pageType text,
  lastSaved timestamp with time zone,
  dynamic boolean DEFAULT false,
  libRefId uuid,
  dynamicSlugCustom character varying DEFAULT ''::character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  tracking jsonb DEFAULT '{}'::jsonb,
  jsonld jsonb DEFAULT '{}'::jsonb,
  globalJsonLds jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT app_pages_pkey PRIMARY KEY (id),
  CONSTRAINT app_pages_app_fkey FOREIGN KEY (app) REFERENCES public.apps(id),
  CONSTRAINT app_pages_parent_fkey FOREIGN KEY (parent) REFERENCES public.app_pages(id)
);
CREATE TABLE public.app_pages_metadata (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  slug character varying NOT NULL,
  pageId uuid DEFAULT gen_random_uuid(),
  publishedAt timestamp with time zone,
  pageType character varying,
  pageBlocks character varying,
  dataBindings character varying,
  pageContent character varying,
  dataProviders character varying,
  app uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT app_pages_metadata_pkey PRIMARY KEY (slug, app)
);
CREATE TABLE public.app_pages_online (
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  slug text NOT NULL,
  lang text NOT NULL DEFAULT ''::text,
  seo jsonb DEFAULT '{}'::jsonb,
  app uuid NOT NULL,
  buildTime boolean DEFAULT false,
  id uuid NOT NULL,
  name text NOT NULL,
  primaryPage uuid,
  blocks jsonb DEFAULT '[]'::jsonb,
  currentEditor text,
  changes jsonb,
  collection text DEFAULT 'page'::text,
  partialBlocks text,
  links text,
  online boolean DEFAULT true,
  pageType text,
  parent uuid,
  lastSaved timestamp with time zone,
  dynamic boolean DEFAULT false,
  libRefId uuid,
  dynamicSlugCustom character varying DEFAULT ''::character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  tracking jsonb DEFAULT '{}'::jsonb,
  jsonld jsonb DEFAULT '{}'::jsonb,
  globalJsonLds jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT app_pages_online_pkey PRIMARY KEY (id),
  CONSTRAINT app_pages_online_app_fkey FOREIGN KEY (app) REFERENCES public.apps(id)
);
CREATE TABLE public.app_pages_revisions (
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  slug text NOT NULL,
  lang text NOT NULL DEFAULT ''::text,
  seo jsonb DEFAULT '{}'::jsonb,
  app uuid NOT NULL,
  buildTime boolean DEFAULT false,
  id uuid NOT NULL,
  name text NOT NULL,
  primaryPage uuid,
  blocks jsonb DEFAULT '[]'::jsonb,
  currentEditor text,
  changes jsonb,
  collection text DEFAULT 'page'::text,
  partialBlocks text,
  links text,
  online boolean DEFAULT true,
  pageType text,
  parent uuid,
  lastSaved timestamp with time zone,
  dynamic boolean DEFAULT false,
  uid uuid NOT NULL DEFAULT gen_random_uuid(),
  type character varying DEFAULT 'published'::character varying,
  libRefId uuid,
  dynamicSlugCustom character varying DEFAULT ''::character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  tracking jsonb DEFAULT '{}'::jsonb,
  jsonld jsonb DEFAULT '{}'::jsonb,
  globalJsonLds jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT app_pages_revisions_pkey PRIMARY KEY (uid),
  CONSTRAINT app_pages_revisions_app_fkey FOREIGN KEY (app) REFERENCES public.apps(id)
);
CREATE TABLE public.app_user_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  user uuid,
  planId text DEFAULT 'FREE'::text,
  nextBilledAt timestamp without time zone NOT NULL,
  status text DEFAULT 'ACTIVE'::text,
  data jsonb,
  priceId text,
  subscriptionId text,
  client uuid,
  CONSTRAINT app_user_plans_pkey PRIMARY KEY (id),
  CONSTRAINT app_user_plans_client_fkey FOREIGN KEY (client) REFERENCES public.clients(id),
  CONSTRAINT app_user_plans_user_fkey FOREIGN KEY (user) REFERENCES auth.users(id)
);
CREATE TABLE public.app_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  user uuid,
  app uuid,
  role character varying DEFAULT 'editor'::character varying,
  permissions jsonb,
  status text NOT NULL DEFAULT 'active'::text,
  CONSTRAINT app_users_pkey PRIMARY KEY (id),
  CONSTRAINT app_users_user_fkey FOREIGN KEY (user) REFERENCES auth.users(id),
  CONSTRAINT app_users_app_fkey FOREIGN KEY (app) REFERENCES public.apps(id)
);
CREATE TABLE public.apps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  name character varying,
  user uuid,
  settings jsonb DEFAULT '{}'::jsonb,
  theme jsonb DEFAULT '{}'::jsonb,
  fallbackLang text DEFAULT 'en'::text,
  languages jsonb DEFAULT '[]'::jsonb,
  changes jsonb,
  configData jsonb,
  deletedAt timestamp with time zone,
  client uuid,
  CONSTRAINT apps_pkey PRIMARY KEY (id),
  CONSTRAINT apps_client_fkey FOREIGN KEY (client) REFERENCES public.clients(id),
  CONSTRAINT apps_user_fkey FOREIGN KEY (user) REFERENCES auth.users(id)
);
CREATE TABLE public.apps_online (
  id uuid NOT NULL,
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  name character varying,
  user uuid,
  settings jsonb DEFAULT '{}'::jsonb,
  theme jsonb DEFAULT '{}'::jsonb,
  fallbackLang text DEFAULT 'en'::text,
  languages jsonb DEFAULT '[]'::jsonb,
  changes jsonb,
  configData jsonb,
  apiKey text,
  deletedAt timestamp with time zone,
  client uuid,
  CONSTRAINT apps_online_pkey PRIMARY KEY (id),
  CONSTRAINT apps_online_client_fkey FOREIGN KEY (client) REFERENCES public.clients(id),
  CONSTRAINT apps_online_user_fkey FOREIGN KEY (user) REFERENCES auth.users(id)
);
CREATE TABLE public.chai_studio_installs (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  installUuid uuid,
  installDatetime timestamp with time zone,
  lastOpened timestamp with time zone,
  installVersion character varying,
  latestVersion character varying,
  status character varying DEFAULT 'ACTIVE'::character varying,
  os character varying,
  stats jsonb,
  licenseKey text,
  purchaseEmail text,
  country text,
  licenseType text,
  CONSTRAINT chai_studio_installs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  name text,
  status text DEFAULT 'active'::text,
  billingStartDate date,
  startDate date,
  settings jsonb DEFAULT '{}'::jsonb,
  loginHtml text,
  features jsonb DEFAULT '{}'::jsonb,
  paymentConfig jsonb DEFAULT '{}'::jsonb,
  theme text,
  helpHtml text,
  madeWithBadge text,
  CONSTRAINT clients_pkey PRIMARY KEY (id)
);
CREATE TABLE public.do_not_delete (
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  password boolean NOT NULL DEFAULT false,
  user uuid NOT NULL UNIQUE,
  email text NOT NULL,
  name text,
  CONSTRAINT do_not_delete_pkey PRIMARY KEY (user),
  CONSTRAINT user_meta_user_fkey FOREIGN KEY (user) REFERENCES auth.users(id)
);
CREATE TABLE public.libraries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  name character varying,
  app uuid,
  type character varying,
  status text NOT NULL DEFAULT 'active'::text,
  client uuid,
  CONSTRAINT libraries_pkey PRIMARY KEY (id),
  CONSTRAINT libraries_client_fkey FOREIGN KEY (client) REFERENCES public.clients(id),
  CONSTRAINT libraries_app_fkey FOREIGN KEY (app) REFERENCES public.apps(id)
);
CREATE TABLE public.library_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  library uuid,
  name text,
  description text,
  blocks jsonb DEFAULT '[]'::jsonb,
  preview text,
  group text DEFAULT 'general'::text,
  user text,
  html text,
  CONSTRAINT library_items_pkey PRIMARY KEY (id),
  CONSTRAINT library_items_library_fkey FOREIGN KEY (library) REFERENCES public.libraries(id)
);
CREATE TABLE public.library_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  user text,
  name text,
  description text,
  pageId uuid,
  pageType text,
  library uuid,
  preview text,
  CONSTRAINT library_templates_pkey PRIMARY KEY (id),
  CONSTRAINT library_templates_library_fkey FOREIGN KEY (library) REFERENCES public.libraries(id)
);